#!/bin/bash

# Verifica se o arquivo existe antes de rodar
if [ -f "/home/fgv/texto.txt" ]; then
    egrep -o "[a-zA-Z]+(?:_[a-zA-Z]+)+" /home/fgv/texto.txt
else
    echo "Erro: O arquivo /home/fgv/texto.txt não existe!"
fi

