[project]
name = "env-prog"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "geopandas>=1.1.0",
    "jupyter>=1.1.1",
    "mapclassify>=2.8.1",
    "matplotlib>=3.10.3",
    "mosqlient>=1.9.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "sympy>=1.14.0",
]
